CREATE TABLE IF NOT EXISTS product_master_snapshot (
  product_snapshot_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_product_id VARCHAR(64) NOT NULL,
  leaf_category_id VARCHAR(128) NOT NULL,
  leaf_category_name VARCHAR(255) NOT NULL,
  product_name VARCHAR(512) NOT NULL,
  brand_name VARCHAR(255) NOT NULL,
  shop_name VARCHAR(255) NULL,
  brand_asset_level VARCHAR(16) NOT NULL,
  price_band VARCHAR(16) NOT NULL,
  price_source VARCHAR(64) NOT NULL,
  financial_risk_level VARCHAR(16) NOT NULL,
  core_jtbd VARCHAR(128) NOT NULL,
  trust_barrier_level VARCHAR(16) NOT NULL,
  cognitive_barrier_level VARCHAR(16) NOT NULL,
  habit_switch_barrier_level VARCHAR(16) NOT NULL,
  diagnosis_version VARCHAR(128) NOT NULL,
  diagnosis_generated_at DATETIME(6) NOT NULL,
  snapshot_hash CHAR(64) NOT NULL,
  provenance_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (product_snapshot_id),
  UNIQUE KEY uq_product_snapshot (source_product_id, snapshot_hash),
  KEY idx_product_latest (source_product_id, diagnosis_generated_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS video_blueprint_master (
  blueprint_id VARCHAR(32) NOT NULL,
  video_id VARCHAR(64) NOT NULL,
  source_product_id VARCHAR(64) NOT NULL,
  product_snapshot_id BIGINT UNSIGNED NOT NULL,
  request_id VARCHAR(128) NOT NULL,
  generator_version VARCHAR(128) NOT NULL,
  workflow_version VARCHAR(128) NOT NULL,
  storyboard_source VARCHAR(32) NOT NULL,
  semantic_bundle_count INT NOT NULL,
  primary_hec_json JSON NOT NULL,
  secondary_effects_json JSON NOT NULL,
  slider_signature_json JSON NOT NULL,
  risk_flags_json JSON NOT NULL,
  semantic_bundles_json JSON NOT NULL,
  segment_to_bundle_map_json JSON NOT NULL,
  bundle_to_segment_range_json JSON NOT NULL,
  provenance_json JSON NOT NULL,
  idempotency_key CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (blueprint_id),
  UNIQUE KEY uq_blueprint_idempotency (idempotency_key),
  KEY idx_blueprint_video (video_id),
  KEY idx_blueprint_product (source_product_id),
  KEY idx_blueprint_snapshot (product_snapshot_id),
  CONSTRAINT fk_blueprint_snapshot FOREIGN KEY (product_snapshot_id)
    REFERENCES product_master_snapshot(product_snapshot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS video_segment_fact_table (
  segment_record_id VARCHAR(32) NOT NULL,
  blueprint_id VARCHAR(32) NOT NULL,
  video_id VARCHAR(64) NOT NULL,
  source_product_id VARCHAR(64) NOT NULL,
  segment_id VARCHAR(32) NOT NULL,
  segment_order INT NOT NULL,
  start_sec DECIMAL(10,3) NOT NULL,
  end_sec DECIMAL(10,3) NOT NULL,
  bundle_id VARCHAR(64) NULL,
  shot_size VARCHAR(64) NOT NULL,
  camera_movement VARCHAR(128) NOT NULL,
  lighting_tone VARCHAR(128) NOT NULL,
  visual_subject VARCHAR(1024) NOT NULL,
  key_objects_json JSON NOT NULL,
  actions_json JSON NOT NULL,
  ocr_facts_json JSON NOT NULL,
  audio_facts_json JSON NOT NULL,
  rhythm_facts_json JSON NOT NULL,
  annotation_json JSON NOT NULL,
  provenance_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (segment_record_id),
  UNIQUE KEY uq_blueprint_segment (blueprint_id, segment_id),
  KEY idx_segment_blueprint_order (blueprint_id, segment_order),
  KEY idx_segment_video (video_id),
  KEY idx_segment_product (source_product_id),
  CONSTRAINT fk_segment_blueprint FOREIGN KEY (blueprint_id)
    REFERENCES video_blueprint_master(blueprint_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
